### ISSUE TITLE
TimeFromNow issue in French Locale

### ISSUE THREAD

**Issue by fredgaume** [anandbn/timeline-lwc#21]
The activityTimeLine shows 5 month ago in the month group header while being mid-may cause of a miscalculation!

Here is the example as of the 19th of may:
(https://user-images.githubusercontent.com/47078179/82313111-34689700-99c8-11ea-89b2-21dfbe648a63.png)

**Comment by anandbn** [comment]
Thanks @fredgaume - I'll take a look to see if I can reproduce. Please get the latest version v1.44 from https://login.salesforce.com/packaging/installPackage.apexp?p0=04t4T000000x9MX&isdtp=p1 to see if the problem goes away. I have resolved a few localiation bugs. I had someone in Germany test a date in May and that as working as expected.

**Comment by fredgaume** [comment]
Hi @anandbn , sorry but this particular bug has not been fixed in the last updates you made :)
Seems it comes from groupByMonth method in ActivityTimeLine.js where timeFromNow is calculated relatively to the monthValue string and not the firstOfMonth or the key
    monthItem.monthValue = moment(key).format("MMM  •  YYYY");
    monthItem.firstOfMonth = moment(key).format("YYYY-MM-01");
    monthItem.timeFromNow = moment(monthItem.monthValue).fromNow();

**Comment by anandbn** [comment]
excellent find @fredgaume. I'll fix it in the next version. Thanks for testing.

**Comment by fredgaume** [comment]
Thanks & Congrats for the great job on this component!

**Comment by anandbn** [comment]
@fredgaume - this should be resolved in the latest release at https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000G0yN3UAJ
