### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by willbillmorgan** [anandbn/timeline-lwc#26]
Hi - I really want to use this. Am trying to deploy using VSCode on a Windows pc. The problem is that the timeline custom object timeline__Timeline_Child_Objects__r isn't in my org and therefore the references to it are failing on deployment.

Am I missing a step. Sorry if this has been answered elsewhere but I wasn't sure where to look. Is there a specific deployment process I need to follow that creates the objects correctly (or do I do it directly into the org?)

**Comment by anandbn** [comment]
@willbillmorgan - `timeline__` is the managed package's namespace so it won't be there in your org. The code here is pretty much the code for the managed package at https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000G0yN3UAJ

For you to deploy this into your org, do a find for `timeline__` and replace it with empty string and then it should deploy. Let me know if that works and I'll update the readme in the repo.

**Comment by willbillmorgan** [comment]
Thanks! I’ll give it a shot.

**Comment by willbillmorgan** [comment]
This seems to have reduced the errors considerably. If I try to deploy into a fresh Sandbox, the errors on deployment, after replacing all timeline__ with blank are:

ERRORS                                                                                                           

force-app\main\default\translations\en_US.translation-meta.xml                                          
Not available for deploy for this organization
                                                                   
force-app\main\default\lwc\activityTimeline\activityTimeline.js                                         
Invalid reference c.Upcoming of type label in file activityTimeline.js
                                           
force-app\main\default\layouts\Timeline_Configuration__c-Timeline Configuration Layout.layout-meta.xml  In field: QuickAction - no QuickAction named Timeline_Configuration__c.Add_Child_Object found
                    
force-app\main\default\flows\Add_Child_object_to_Config.flow-meta.xml                                   cmp_Select_Apex_Class (Screen Component) - We can't find an extension called "timeline:selectApexRecordProvider".

force-app\main\default\objects\Timeline_Configuration__c\Timeline_Configuration__c.object-meta.xml      Timeline_Configuration_Record_Page does not exist or is not a valid override for action View.       

I very much appreciate your help with this.

I could perhaps just use the package from the AppExchange, however I want to use this on an appPage (rather than a record page) and dynamically change the parent object (which is always an account)

**Comment by anandbn** [comment]
@willbillmorgan - perhaps we can get on a call to understand the use case. Email me at anarasimhan@salesforce.com
