### ISSUE TITLE
Error when a child object is created for Task, and if Parent object has Email records related to it.

### ISSUE THREAD

**Issue by JoelRisley** [anandbn/timeline-lwc#27]
Receiving error from @wire property due to "Cannot read property 'Name' of undefined.". This is only notices when the Child object is configured for Task (standard relationship), and is only seen if there are Email Messages related to the Parent object. The error is not seen when there are no Email Messages related to the Parent object. Alternatively, creating a custom lookup from the EmailMessage to the Parent object, and using that to configure the Child object, does not throw the error.

![Error](https://user-images.githubusercontent.com/29860395/88617318-f5378000-d0b3-11ea-90c5-6c8fbe383381.PNG)

**Comment by anandbn** [comment]
@JoelRisley - what version of the package is this error occurring? In the more recent version this error has been resolved.
