### ISSUE TITLE
Timeline Item Title Link

### ISSUE THREAD

**Issue by vincekruger** [anandbn/timeline-lwc#29]
Is it possible to construct the title link with an `href` instead of using javascript to navigate to the record as well as have a configuration option to set the default target?

This will allow users the choice to open the record in a new tab and give the admin the option to force items to open in a new tab.

**Comment by issacchern** [comment]
Also, using javascript to navigate is not reliable as using href. This is some errors when trying to open the link:

![image](https://user-images.githubusercontent.com/10298780/139727621-82d52d43-2bb8-4344-8763-284f30553ea5.png)
