### ISSUE TITLE
AttachedContentNote fields can be displayed in Title and Subtitle but cannot be displayed in "Fields to Display"

### ISSUE THREAD

**Issue by cyruschiucy** [anandbn/timeline-lwc#40]
Configuration:
![image](https://user-images.githubusercontent.com/132893854/236790014-ff1b75f7-f511-40ba-b673-e70e42cd40b3.png)

Result of display:
![image](https://user-images.githubusercontent.com/132893854/236790115-17ae03ab-b813-4663-84eb-551c16b42ca5.png)

**Comment by anandbn** [comment]
@cyruschiucy ContentNote is a special object and it's intent is to display the underlying note associated with it.
